// ProcessIQ frontend controller. API and presentation are kept separate.
const API='/api';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,opt={}){const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text()||r.status);return r.json()}
const cls=s=>s>=75?'high':s>=55?'medium':'low';
function openModal(){ $('modalBg').classList.add('open') } function closeModal(){ $('modalBg').classList.remove('open') }
async function dashboard(){const d=await api(API+'/dashboard');$('metrics').innerHTML=[['Total processes',d.total_processes],['Average opportunity score',d.average_score+'/100'],['High priority opportunities',d.high_priority],['Medium priority opportunities',d.medium_priority]].map(x=>`<div class="metric"><b>${esc(x[1])}</b><span>${esc(x[0])}</span></div>`).join('');$('departmentBars').innerHTML=d.department_scores.map(x=>`<div class="barrow"><div>${esc(x.department)}</div><div class="track"><div class="bar" style="width:${Math.max(0,Math.min(x.average_score,100))}%"></div></div><b>${x.average_score}</b></div>`).join('')}
async function filters(){const p=await api(API+'/processes');const vals=(field)=>[...new Set(p.map(x=>x[field]))].sort();$('department').innerHTML='<option value="">All departments</option>'+vals('department').map(x=>`<option>${esc(x)}</option>`).join('');$('industry').innerHTML='<option value="">All industries</option>'+vals('industry').map(x=>`<option>${esc(x)}</option>`).join('')}
async function load(){try{$('status').textContent='Loading processes...';const q=new URLSearchParams();if($('search').value.trim())q.set('search',$('search').value.trim());if($('department').value)q.set('department',$('department').value);if($('industry').value)q.set('industry',$('industry').value);const p=await api(API+'/processes?'+q);$('rows').innerHTML=p.length?p.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td><td><span class="badge">${esc(x.department)}</span></td><td>${esc(x.industry)}</td><td>${Number(x.annual_volume).toLocaleString()}</td><td class="${cls(x.opportunity_score)}">${x.opportunity_score}/100</td><td>${esc(x.recommendation)}</td><td><button data-id="${x.id}">View</button></td></tr>`).join(''):'<tr><td colspan="8">No processes matched your search.</td></tr>';$('status').textContent=`${p.length} process${p.length===1?'':'es'} found.`;document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>view(+b.dataset.id))}catch(e){$('status').textContent='Error: '+e.message}}
async function view(id){try{const p=await api(API+'/processes/'+id);const inputs=[['Annual volume',Number(p.annual_volume).toLocaleString()],['Manual effort',p.manual_effort_pct+'%'],['Error rate',p.error_rate_pct+'%'],['Business impact',p.business_impact+'/10'],['Data quality',p.data_quality+'/10'],['Implementation complexity',p.implementation_complexity+'/10'],['Risk level',p.risk_level+'/10']];$('modalContent').innerHTML=`<h2>${esc(p.name)}</h2><p><span class="badge">${esc(p.department)}</span> <span class="badge">${esc(p.industry)}</span></p><h1 class="${cls(p.opportunity_score)}">${p.opportunity_score}/100</h1><p><b>${esc(p.recommendation)}</b></p><h3>Why this score?</h3><p>${esc(p.explanation)}</p><h3>Suggested AI approach</h3><p>${esc(p.suggested_solution)}</p><h3>Key inputs</h3><div class="detailgrid">${inputs.map(x=>`<div class="detailitem"><b>${x[0]}</b><br>${x[1]}</div>`).join('')}</div><h3>Score breakdown</h3><ul>${Object.entries(p.score_breakdown).map(([k,v])=>`<li>${esc(k.replaceAll('_',' '))}: ${v} points</li>`).join('')}</ul>`;openModal()}catch(e){alert(e.message)}}
function showAdd(){const f=[['name','Process name','text',''],['department','Department','text',''],['industry','Industry','text','General'],['annual_volume','Annual volume','number',''],['manual_effort_pct','Manual effort (%)','number',''],['error_rate_pct','Error rate (%)','number',''],['business_impact','Business impact (0-10)','number',''],['data_quality','Data quality (0-10)','number',''],['implementation_complexity','Implementation complexity (0-10)','number',''],['risk_level','Risk level (0-10)','number','']];$('modalContent').innerHTML=`<h2>Add a new process</h2><p>This demonstrates runtime onboarding. New business data appears without changing application code.</p><form id="addForm"><div class="formgrid">${f.map(x=>`<div class="field"><label>${x[1]}</label><input name="${x[0]}" type="${x[2]}" value="${x[3]}" ${x[2]=='number'?'step="any"':''} required></div>`).join('')}<div class="field full"><label>Description</label><textarea name="description" required placeholder="Describe the business process"></textarea></div></div><div class="actions"><button>Save process</button><button type="button" id="cancel" class="secondary">Cancel</button></div></form>`;$('addForm').onsubmit=add;$('cancel').onclick=closeModal;openModal()}
async function add(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));['annual_volume','manual_effort_pct','error_rate_pct','business_impact','data_quality','implementation_complexity','risk_level'].forEach(k=>data[k]=Number(data[k]));try{const r=await api(API+'/processes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});alert('Process "'+r.name+'" added successfully.');closeModal();await init()}catch(err){alert('Unable to add process: '+err.message)}}
async function ask(){const q=$('question').value.trim();if(!q){$('answer').textContent='Please enter a question.';return}$('answer').textContent='Analyzing current process data...';try{$('answer').textContent=(await api(API+'/ask?question='+encodeURIComponent(q))).answer}catch(e){$('answer').textContent='Unable to answer: '+e.message}}
async function init(){try{await Promise.all([dashboard(),filters()]);await load()}catch(e){$('status').textContent='Application error: '+e.message}}
$('searchButton').onclick=load;$('search').onkeydown=e=>{if(e.key==='Enter')load()};$('department').onchange=load;$('industry').onchange=load;$('clearButton').onclick=()=>{$('search').value='';$('department').value='';$('industry').value='';load()};$('addButton').onclick=showAdd;$('askButton').onclick=ask;$('question').onkeydown=e=>{if(e.key==='Enter')ask()};$('closeModal').onclick=closeModal;$('modalBg').onclick=e=>{if(e.target===$('modalBg'))closeModal()};document.onkeydown=e=>{if(e.key==='Escape')closeModal()};init();
